### ISSUE TITLE
Build python-numpy in BREW

### ISSUE THREAD

**Issue by kholdaway** [redhat-discovery/discovery-server#46]

**Comment by myersCody** [comment]
Official Build
https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=20707528

A yum repository for the build of python-numpy-1.10.4-7.el7 (task 20707528) is available at:

http://brew-task-repos.usersys.redhat.com/repos/official/python-numpy/1.10.4/7.el7/

You can install the rpms locally by putting this .repo file in your /etc/yum.repos.d/ directory:

http://brew-task-repos.usersys.redhat.com/repos/official/python-numpy/1.10.4/7.el7/python-numpy-1.10.4-7.el7.repo

RPMs and build logs can be found in the following locations:
http://brew-task-repos.usersys.redhat.com/repos/official/python-numpy/1.10.4/7.el7/x86_64/

The full list of available rpms is:
http://brew-task-repos.usersys.redhat.com/repos/official/python-numpy/1.10.4/7.el7/x86_64/python-numpy-1.10.4-7.el7.src.rpm
http://brew-task-repos.usersys.redhat.com/repos/official/python-numpy/1.10.4/7.el7/x86_64/python-numpy-f2py-1.10.4-7.el7.x86_64.rpm
http://brew-task-repos.usersys.redhat.com/repos/official/python-numpy/1.10.4/7.el7/x86_64/python-numpy-1.10.4-7.el7.x86_64.rpm
